#ifndef CLINT_H_
#define CLINT_H_

#define CLINT_BASE 0x2000000L
#define CLINT_SIZE 0x10000
#define CLINT_END (CLINT_BASE + CLINT_SIZE)
#define CLINT_MTIMECMP(HART_ID) (CLINT_BASE + 0x4000 + 8 * (HART_ID))
#define CLINT_MTIME (CLINT_BASE + 0xBFF8)

#endif
