#ifndef TRAP_HANDLE_H_
#define TRAP_HANDLE_H_

#define SCAUSE_INTERRPUT_MASK (1L << 63)
#define SCAUSE_SSI (SCAUSE_INTERRPUT_MASK | 1)
#define SCAUSE_SEI (SCAUSE_INTERRPUT_MASK | 9)
#define SCAUSE_ECALL_FROM_U 8

#endif
